---
# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: fasterer
  name: Suggest speed improvements in Ruby
  description: Use fasterer to suggest speed improvements in Ruby
  entry: run-fasterer
  language: ruby
  types: ['ruby']

- id: forbid-binary
  name: Forbid binaries
  description: Forbid binary files from being committed
  entry: pre_commit_hooks/forbid-binary.sh
  language: script
  types: ['binary']

- id: forbid-space-in-indent
  name: Forbid spaces in indentation
  description: Forbid spaces in indentation
  entry: pre_commit_hooks/forbid-space-in-indent.sh
  language: script

- id: git-check
  name: Check for conflict markers and core.whitespace errors
  # yamllint disable-line rule:line-length
  description: Use git to check for conflict markers and core.whitespace errors, respecting .gitattributes
  entry: pre_commit_hooks/git-check.sh
  language: script

- id: git-dirty
  name: Check if the git tree is dirty
  description: Detect if git tree contains modified, staged, or untracked files
  entry: pre_commit_hooks/git-dirty.sh
  language: script

- id: reek
  name: Find ruby code smells
  description: Use reek to find ruby code smells
  entry: run-reek
  language: ruby
  types: ['ruby']

- id: rubocop
  name: Check Ruby style with rubocop and rubocop-rspec
  description: Enforce Ruby style guide with rubocop and rubocop-rspec
  entry: run-rubocop
  language: ruby
  types: ['ruby']

- id: shellcheck
  name: Test shell scripts with shellcheck
  description: Shell scripts conform to shellcheck
  entry: pre_commit_hooks/shellcheck.sh
  language: script
  types: [shell]
  args: [-e, SC1091]
  additional_dependencies: [shellcheck]

- id: shfmt
  name: Check shell style with shfmt
  language: script
  entry: pre_commit_hooks/shfmt.sh
  types: [shell]
  args: ['-l', '-i', '2', '-ci']
  additional_dependencies: [shfmt]
