---
# This file configures https://pre-commit.com/
# to use specific hooks and options.

fail_fast: false

repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    sha: 1.3.2
    hooks:
      - id: forbid-binary
        exclude: >
          (?x)^(
            ci/fixtures/one-byte-binary
          )$
      - id: git-check  # Configure in .gitattributes
      - id: git-dirty  # Configure in .gitignore
      - id: shellcheck

  - repo: local
    hooks:
      - id: forbid-binary
        name: forbid-binary (local)
        language: script
        entry: pre_commit_hooks/forbid-binary.sh
        types: ['binary']
        exclude: >
          (?x)^(
            ci/fixtures/one-byte-binary
          )$

      - id: forbid-space-in-indent
        name: forbid-space-in-indent (local)
        language: script
        entry: pre_commit_hooks/forbid-space-in-indent.sh
        exclude: ^.*$

      - id: git-dirty
        name: git-dirty (local)
        language: script
        entry: pre_commit_hooks/git-dirty.sh

      - id: shellcheck
        name: shellcheck (local)
        language: script
        entry: pre_commit_hooks/shellcheck.sh
        types: [shell]
        args: [-e, SC1091]
        additional_dependencies: [shellcheck]

  - repo: https://github.com/adrienverge/yamllint.git
    sha: v1.11.0
    hooks:
      - id: yamllint
        args: ['--format', 'parsable', '--strict']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.3
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    sha: v1.1.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
